### ISSUE TITLE
Null pointer exception on missing footnote

### ISSUE THREAD

**Issue by io7m** [io7m/r2#59]
```
Caused by: kotlin.KotlinNullPointerException
	at com.io7m.kstructural.core.evaluator.KSEvaluator$Context$checkFootnoteReferences$act_refs$1.invoke(KSEvaluator.kt:572)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$Context$checkFootnoteReferences$act_refs$1.invoke(KSEvaluator.kt:90)
	at com.io7m.kstructural.core.KSResult$Companion.listMap(KSResult.kt:134)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$Context.checkFootnoteReferences(KSEvaluator.kt:568)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$evaluate$1$1.invoke(KSEvaluator.kt:709)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$evaluate$1$1.invoke(KSEvaluator.kt:86)
	at com.io7m.kstructural.core.KSResult$Companion.flatMap(KSResult.kt:109)
	at com.io7m.kstructural.core.KSResult.flatMap(KSResult.kt:64)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$evaluate$1.invoke(KSEvaluator.kt:708)
	at com.io7m.kstructural.core.evaluator.KSEvaluator$evaluate$1.invoke(KSEvaluator.kt:86)
	at com.io7m.kstructural.core.KSResult$Companion.flatMap(KSResult.kt:105)
	at com.io7m.kstructural.core.KSResult.flatMap(KSResult.kt:64)
	at com.io7m.kstructural.core.evaluator.KSEvaluator.evaluate(KSEvaluator.kt:706)
	at com.io7m.kstructural.frontend.KSParseAndEvaluate.lambda$parseAndEvaluate$0(KSParseAndEvaluate.java:103)
	at com.io7m.kstructural.core.KSBlockMatch.match(KSBlockMatch.kt:27)
	at com.io7m.kstructural.frontend.KSParseAndEvaluate.parseAndEvaluate(KSParseAndEvaluate.java:96)
	at com.io7m.kstructural.frontend.KSOpCompileXHTML.call(KSOpCompileXHTML.java:139)
	at com.io7m.kstructural.frontend.KSOpCompileXHTML.call(KSOpCompileXHTML.java:44)
	at com.io7m.kstructural.maven_plugin.KSCompileXHTMLMojo.execute(KSCompileXHTMLMojo.java:190)
```

**Comment by io7m** [comment]
Misfiled here instead of at [kstructural](/io7m/kstructural).
